// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.github.fabriciolfj.api.grpc.v1;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.fabriciolfj.v1.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string document = 1;</code>
   * @return The document.
   */
  java.lang.String getDocument();
  /**
   * <code>string document = 1;</code>
   * @return The bytes for document.
   */
  com.google.protobuf.ByteString
      getDocumentBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
